# Generated by Django 4.1.4 on 2025-02-10 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_artist_music_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=600)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='music',
            old_name='author',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='music_file',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='music',
            name='price',
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
