# Generated by Django 4.1.4 on 2025-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmusic',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterModelTable(
            name='uploadedmusic',
            table='UploadedMusic',
        ),
    ]
